"""Add User to Todo

Revision ID: 52cde7308f57
Revises: fbca76a77094
Create Date: 2023-10-24 10:48:55.045972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cde7308f57'
down_revision = 'fbca76a77094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_Todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_todo_Todo_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'auth_User', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_Todo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_todo_Todo_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
